
services:
  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/zesenzhu/xb-fe:latest}
    container_name: xbnest-frontend-prod
    restart: always
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    environment:
      PORT: 8080
      HOSTNAME: "0.0.0.0"

  gateway:
    image: caddy:alpine
    container_name: xbnest-gateway
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
